### ISSUE TITLE
Grunt serve not running

### ISSUE THREAD

**Issue by rridhan** [ffffranklin/generator-tumblr-theme#36]
If i try to run `grunt` or `grunt serve` from terminal I got this erro message:
```
Running "sass:dist" (sass) task

Running "connect:main" (connect) task
Started connect web server on http://0.0.0.0:9000

Running "spottr" task
Spottr: Created Server "http://localhost:8080"

Running "open:dev" (open) task
Warning: Command failed: /bin/sh -c Chrome "http://localhost:9000"
/bin/sh: 1: Chrome: not found
 Use --force to continue.
```
running on Ubuntu machine (14.04) with NodeJS v4.2.1. and npm 2.14.7 (installing through NVM).

**Comment by ffffranklin** [comment]
Thanks @rridhan.  By default node-open requires Chrome but I'll omit that in the next release.  To fix remove the `app: 'Google Chrome'` option from the open:dev task config in your `Gruntfile.js`
